/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */
plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.31"
//    id ("org.jetbrains.kotlin.multiplatform") version "1.4.30"
    id("org.jetbrains.kotlin.plugin.serialization") version "1.4.30"
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenCentral()
    google()
    jcenter()
    maven(url = "https://jitpack.io")
}

dependencies {

    //OkHttp
    implementation("com.squareup.okhttp3:okhttp:4.9.0")

    //OkHttp MockWeb Server for testing
//    testImplementation("com.squareup.okhttp3:mockwebserver:4.9.0")

    //Gson for type converter kotlin
    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.1.0")


    //Retrofit for HTTP calls
    implementation("com.squareup.retrofit2:retrofit:2.9.0")

    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Google Play Services - Location services
//    implementation("com.google.android.gms:play-services-location:18.0.0")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
